# This file is part of the SV-Benchmarks collection of verification tasks:
# https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
#
# SPDX-FileCopyrightText: 2022 Jana (Philipp) Berger
#
# SPDX-License-Identifier: GPL-3.0-or-later

LEVEL := ../

GCC_WARNINGS := \
	-Wno-tautological-compare

CLANG_WARNINGS := \
	-Wno-tautological-constant-out-of-range-compare \
	-Wno-tautological-compare \
	-Wno-literal-conversion

include $(LEVEL)/Makefile.config
