// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version bfcfb8b
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern void abort(void);
void reach_error() {}
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_4;  // BV with 8 bits
  const SORT_4 mask_SORT_4 = (SORT_4)-1 >> (sizeof(SORT_4) * 8 - 8);
  const SORT_4 msb_SORT_4 = (SORT_4)1 << (8 - 1);
  typedef unsigned char SORT_16;  // BV with 2 bits
  const SORT_16 mask_SORT_16 = (SORT_16)-1 >> (sizeof(SORT_16) * 8 - 2);
  const SORT_16 msb_SORT_16 = (SORT_16)1 << (2 - 1);
  typedef unsigned int SORT_44;  // BV with 32 bits
  const SORT_44 mask_SORT_44 = (SORT_44)-1 >> (sizeof(SORT_44) * 8 - 32);
  const SORT_44 msb_SORT_44 = (SORT_44)1 << (32 - 1);
  // Initializing constants ...
  const SORT_4 var_5 = 0;
  const SORT_4 var_8 = 255;
  const SORT_1 var_12 = 1;
  const SORT_16 var_17 = 0;
  const SORT_4 var_21 = 1;
  const SORT_4 var_23 = 63;
  const SORT_4 var_29 = 7;
  const SORT_16 var_35 = 2;
  const SORT_16 var_38 = 1;
  const SORT_44 var_45 = 0;
  const SORT_44 var_46 = 1;
  const SORT_44 var_52 = 2;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_1 input_3;
  // Collecting state declarations ...
  SORT_4 state_6 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_16 state_18 = __VERIFIER_nondet_uchar() & mask_SORT_16;
  // Initializing states ...
  SORT_4 init_7_arg_1 = var_5;
  state_6 = init_7_arg_1;
  SORT_16 init_19_arg_1 = var_17;
  state_18 = init_19_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_3 = __VERIFIER_nondet_uchar();
    input_3 = input_3 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_4 var_9_arg_0 = state_6;
    SORT_4 var_9_arg_1 = var_8;
    SORT_1 var_9 = var_9_arg_0 != var_9_arg_1;
    SORT_1 var_13_arg_0 = var_9;
    SORT_1 var_13 = ~var_13_arg_0;
    SORT_1 var_14_arg_0 = var_12;
    SORT_1 var_14_arg_1 = var_13;
    SORT_1 var_14 = var_14_arg_0 & var_14_arg_1;
    var_14 = var_14 & mask_SORT_1;
    SORT_1 bad_15_arg_0 = var_14;
    __VERIFIER_assert(!(bad_15_arg_0));
    // Computing next states ...
    SORT_16 var_39_arg_0 = state_18;
    SORT_16 var_39_arg_1 = var_38;
    SORT_1 var_39 = var_39_arg_0 == var_39_arg_1;
    SORT_16 var_36_arg_0 = state_18;
    SORT_16 var_36_arg_1 = var_35;
    SORT_1 var_36 = var_36_arg_0 == var_36_arg_1;
    SORT_1 var_40_arg_0 = var_39;
    SORT_1 var_40_arg_1 = var_36;
    SORT_1 var_40 = var_40_arg_0 | var_40_arg_1;
    var_40 = var_40 & mask_SORT_1;
    SORT_4 var_33_arg_0 = state_6;
    SORT_4 var_33_arg_1 = var_5;
    SORT_1 var_33 = var_33_arg_0 == var_33_arg_1;
    SORT_4 var_32_arg_0 = state_6;
    SORT_4 var_32_arg_1 = var_21;
    SORT_4 var_32 = var_32_arg_0 - var_32_arg_1;
    SORT_1 var_34_arg_0 = var_33;
    SORT_4 var_34_arg_1 = var_23;
    SORT_4 var_34_arg_2 = var_32;
    SORT_4 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    SORT_4 var_30_arg_0 = state_6;
    SORT_4 var_30_arg_1 = var_5;
    SORT_1 var_30 = var_30_arg_0 == var_30_arg_1;
    SORT_4 var_28_arg_0 = state_6;
    SORT_4 var_28_arg_1 = var_21;
    SORT_4 var_28 = var_28_arg_0 - var_28_arg_1;
    SORT_1 var_31_arg_0 = var_30;
    SORT_4 var_31_arg_1 = var_29;
    SORT_4 var_31_arg_2 = var_28;
    SORT_4 var_31 = var_31_arg_0 ? var_31_arg_1 : var_31_arg_2;
    SORT_1 var_37_arg_0 = var_36;
    SORT_4 var_37_arg_1 = var_34;
    SORT_4 var_37_arg_2 = var_31;
    SORT_4 var_37 = var_37_arg_0 ? var_37_arg_1 : var_37_arg_2;
    SORT_16 var_26_arg_0 = state_18;
    SORT_16 var_26_arg_1 = var_17;
    SORT_1 var_26 = var_26_arg_0 == var_26_arg_1;
    SORT_4 var_24_arg_0 = state_6;
    SORT_4 var_24_arg_1 = var_5;
    SORT_1 var_24 = var_24_arg_0 == var_24_arg_1;
    SORT_4 var_22_arg_0 = state_6;
    SORT_4 var_22_arg_1 = var_21;
    SORT_4 var_22 = var_22_arg_0 - var_22_arg_1;
    SORT_1 var_25_arg_0 = var_24;
    SORT_4 var_25_arg_1 = var_23;
    SORT_4 var_25_arg_2 = var_22;
    SORT_4 var_25 = var_25_arg_0 ? var_25_arg_1 : var_25_arg_2;
    SORT_1 var_27_arg_0 = var_26;
    SORT_4 var_27_arg_1 = var_25;
    SORT_4 var_27_arg_2 = state_6;
    SORT_4 var_27 = var_27_arg_0 ? var_27_arg_1 : var_27_arg_2;
    SORT_1 var_41_arg_0 = var_40;
    SORT_4 var_41_arg_1 = var_37;
    SORT_4 var_41_arg_2 = var_27;
    SORT_4 var_41 = var_41_arg_0 ? var_41_arg_1 : var_41_arg_2;
    SORT_1 var_42_arg_0 = input_3;
    SORT_4 var_42_arg_1 = var_5;
    SORT_4 var_42_arg_2 = var_41;
    SORT_4 var_42 = var_42_arg_0 ? var_42_arg_1 : var_42_arg_2;
    var_42 = var_42 & mask_SORT_4;
    SORT_4 next_43_arg_1 = var_42;
    SORT_16 var_61_arg_0 = state_18;
    SORT_16 var_61_arg_1 = var_38;
    SORT_1 var_61 = var_61_arg_0 == var_61_arg_1;
    SORT_16 var_59_arg_0 = state_18;
    SORT_16 var_59_arg_1 = var_35;
    SORT_1 var_59 = var_59_arg_0 == var_59_arg_1;
    SORT_1 var_62_arg_0 = var_61;
    SORT_1 var_62_arg_1 = var_59;
    SORT_1 var_62 = var_62_arg_0 | var_62_arg_1;
    var_62 = var_62 & mask_SORT_1;
    SORT_4 var_56_arg_0 = state_6;
    SORT_4 var_56_arg_1 = var_5;
    SORT_1 var_56 = var_56_arg_0 == var_56_arg_1;
    SORT_1 var_57_arg_0 = var_56;
    SORT_44 var_57_arg_1 = var_45;
    SORT_44 var_57_arg_2 = var_52;
    SORT_44 var_57 = var_57_arg_0 ? var_57_arg_1 : var_57_arg_2;
    SORT_44 var_58_arg_0 = var_57;
    SORT_16 var_58 = var_58_arg_0 >> 0;
    SORT_4 var_53_arg_0 = state_6;
    SORT_4 var_53_arg_1 = var_5;
    SORT_1 var_53 = var_53_arg_0 == var_53_arg_1;
    SORT_1 var_54_arg_0 = var_53;
    SORT_44 var_54_arg_1 = var_52;
    SORT_44 var_54_arg_2 = var_46;
    SORT_44 var_54 = var_54_arg_0 ? var_54_arg_1 : var_54_arg_2;
    SORT_44 var_55_arg_0 = var_54;
    SORT_16 var_55 = var_55_arg_0 >> 0;
    SORT_1 var_60_arg_0 = var_59;
    SORT_16 var_60_arg_1 = var_58;
    SORT_16 var_60_arg_2 = var_55;
    SORT_16 var_60 = var_60_arg_0 ? var_60_arg_1 : var_60_arg_2;
    SORT_16 var_50_arg_0 = state_18;
    SORT_16 var_50_arg_1 = var_17;
    SORT_1 var_50 = var_50_arg_0 == var_50_arg_1;
    SORT_4 var_47_arg_0 = state_6;
    SORT_4 var_47_arg_1 = var_5;
    SORT_1 var_47 = var_47_arg_0 == var_47_arg_1;
    SORT_1 var_48_arg_0 = var_47;
    SORT_44 var_48_arg_1 = var_46;
    SORT_44 var_48_arg_2 = var_45;
    SORT_44 var_48 = var_48_arg_0 ? var_48_arg_1 : var_48_arg_2;
    SORT_44 var_49_arg_0 = var_48;
    SORT_16 var_49 = var_49_arg_0 >> 0;
    SORT_1 var_51_arg_0 = var_50;
    SORT_16 var_51_arg_1 = var_49;
    SORT_16 var_51_arg_2 = state_18;
    SORT_16 var_51 = var_51_arg_0 ? var_51_arg_1 : var_51_arg_2;
    SORT_1 var_63_arg_0 = var_62;
    SORT_16 var_63_arg_1 = var_60;
    SORT_16 var_63_arg_2 = var_51;
    SORT_16 var_63 = var_63_arg_0 ? var_63_arg_1 : var_63_arg_2;
    SORT_1 var_64_arg_0 = input_3;
    SORT_16 var_64_arg_1 = var_17;
    SORT_16 var_64_arg_2 = var_63;
    SORT_16 var_64 = var_64_arg_0 ? var_64_arg_1 : var_64_arg_2;
    var_64 = var_64 & mask_SORT_16;
    SORT_16 next_65_arg_1 = var_64;
    // Assigning next states ...
    state_6 = next_43_arg_1;
    state_18 = next_65_arg_1;
  }
  return 0;
}
